```yaml
name: Docker Security Scan

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t t-aws-lab:latest .

      - name: Scan Docker Image with Trivy
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: t-aws-lab:latest
          format: table
          severity: CRITICAL,HIGH,MEDIUM,LOW
          ignore-unfixed: false
          exit-code: '0'
```
